### ISSUE TITLE
Not working for the micro:bit

### ISSUE THREAD

**Issue by Vegz78** [microsoft/pxt-maker-controller#3]
Hi @pelikhan,

Just read with joy your fun article about "Everything is a Keyboard".

But I am unable to get this pxt-maker-controller extension to work for the micro:bit in the official https://makecode.microbit.org/ editor.

The extension won't load at all into the editor.

Having somewhat similar MCU as many of the maker boards on maker.makecode.com, I had expected it to work also for the micro:bit.

Do you know why the this extension isn't working for the micro:bit, and maybe what your think could be done to make it work?

Br,
Vegard

**Comment by pelikhan** [comment]
Here is a support page with various libraries that will add keyboard emulation support to the microbit. Hope this helps.

https://support.microbit.org/support/solutions/articles/19000071689-can-i-control-my-pc-or-simulate-a-keyboard-and-mouse-

**Comment by Vegz78** [comment]
Yeah, I saw that page, and have been investigating @bsiever's great [microbit-pxt-blehid](https://github.com/bsiever/microbit-pxt-blehid) from there. But sadly it only works for the micro:bit V2.

Though, further investigation of where he got his inspiration, led me today to @fdalvi's fork of a fork of @kshoji's old non-working pxt-bluetooth-keyboard, via @orklann, to his working in older versions [micro-bit-gamepad](https://github.com/fdalvi/micro-bit-game-pad)

So, in a sense, it is already solved over Bluetooth, but still not able to get your pxt-maker-controller extension to work with the micro:bit over usb...(the extension does not load in the micro:bit MakeCode editor)

I thought maybe there were only some dependencies missing or similar in pxt.json, that prevented it from loading in the micro:bite MakeCode, that it would otherwise work? And that you could please comment specifically if you think that is the case, or there are probably bigger hardware related issues preventing this from working with your extension?
https://github.com/microsoft/pxt-maker-controller/blob/master/pxt.json

**Comment by pelikhan** [comment]
It’s not possible on v1 as daplink does not implement keyboard hid.
________________________________
